
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 38;
  public static final int DOSPUNTOS = 36;
  public static final int POR = 28;
  public static final int DIFERENTE = 21;
  public static final int REPEAT = 4;
  public static final int INT = 16;
  public static final int FOR = 6;
  public static final int NOT = 15;
  public static final int MENORIGUAL = 22;
  public static final int IGUALDAD = 20;
  public static final int DIV = 29;
  public static final int UNTIL = 5;
  public static final int IF = 10;
  public static final int ID = 37;
  public static final int MAYORIGUAL = 23;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int MENOS = 27;
  public static final int MENOR = 24;
  public static final int ASIGNACION = 19;
  public static final int FROM = 7;
  public static final int MAYOR = 25;
  public static final int ELSE = 12;
  public static final int TO = 8;
  public static final int LIST = 17;
  public static final int PARI = 30;
  public static final int THEN = 11;
  public static final int CORI = 32;
  public static final int PARD = 31;
  public static final int END = 3;
  public static final int CORD = 33;
  public static final int FALSE = 14;
  public static final int PROCEDURE = 2;
  public static final int DO = 9;
  public static final int PYC = 35;
  public static final int MAS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "END",
  "REPEAT",
  "UNTIL",
  "FOR",
  "FROM",
  "TO",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "TRUE",
  "FALSE",
  "NOT",
  "INT",
  "LIST",
  "RETURN",
  "ASIGNACION",
  "IGUALDAD",
  "DIFERENTE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "MENOR",
  "MAYOR",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "PARI",
  "PARD",
  "CORI",
  "CORD",
  "COMA",
  "PYC",
  "DOSPUNTOS",
  "ID",
  "NUMERO"
  };
}

